# Generated by Django 4.1.5 on 2023-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_logo",
                    models.ImageField(
                        default="/static/img/logo.webp", upload_to="logos/"
                    ),
                ),
                (
                    "instance_favicon",
                    models.ImageField(
                        default="/static/img/favicon.ico", upload_to="favicons/"
                    ),
                ),
                ("instance_title", models.TextField(default="TerraVisu")),
                ("map_bbox_lng_min", models.FloatField(default=-180.0)),
                ("map_bbox_lng_max", models.FloatField(default=180.0)),
                ("map_bbox_lat_min", models.FloatField(default=-90.0)),
                ("map_bbox_lat_max", models.FloatField(default=90.0)),
                ("map_max_zoom", models.FloatField(default=23.0)),
                ("map_min_zoom", models.FloatField(default=0.0)),
                ("map_default_zoom", models.FloatField(default=7.0)),
                ("map_default_lng", models.FloatField(default=2.0)),
                ("map_default_lat", models.FloatField(default=44.0)),
            ],
            options={
                "verbose_name": "Preference",
                "verbose_name_plural": "Preferences",
                "managed": False,
            },
        ),
    ]
