# Generated by Django 4.1.7 on 2023-03-01 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visu", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Preferences",
        ),
    ]
