# Generated by Django 4.1.7 on 2023-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visu", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        blank=True,
                    ),
                ),
                ("href", models.CharField(max_length=255)),
                ("icon", models.ImageField(upload_to="extra_menu_items/")),
            ],
        ),
    ]
