# Generated by Django 4.1.7 on 2023-04-06 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visu", "0004_extramenuitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extramenuitem",
            options={
                "verbose_name": "Extra menu item",
                "verbose_name_plural": "Extra menu items",
            },
        ),
    ]
