# Generated by Django 4.1.8 on 2023-04-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("visu", "0005_alter_extramenuitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="extramenuitem",
            name="limit_to_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="If defined, this extra menu item is only displayed to theses groups members.",
                related_name="extra_menu_items",
                to="auth.group",
            ),
        ),
    ]
