# Generated by Django 4.1.9 on 2023-05-26 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visu", "0006_extramenuitem_limit_to_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spritevalue",
            options={
                "verbose_name": "Sprite icon",
                "verbose_name_plural": "Sprite icons",
            },
        ),
    ]
