# Generated by Django 4.2.27 on 2026-01-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
        ("terra_layer", "0025_auto_20251204_0831"),
        ("visu", "0007_alter_spritevalue_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraSheetFieldThroughModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra sheet field",
                "verbose_name_plural": "Extra sheet fields",
                "ordering": ("block", "order"),
            },
        ),
        migrations.CreateModel(
            name="FeatureSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Sheet name")),
                (
                    "accessible_from",
                    models.ManyToManyField(
                        related_name="feature_sheet",
                        to="terra_layer.layer",
                        verbose_name="Accessible from",
                    ),
                ),
                (
                    "unique_identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geosource.field",
                        verbose_name="Unique identifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature sheet",
                "verbose_name_plural": "Feature sheets",
            },
        ),
        migrations.CreateModel(
            name="SheetBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Block title")),
                (
                    "display_title",
                    models.BooleanField(default=True, verbose_name="Display title"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FIELDS", "Fields"),
                            ("BOOLEANS", "Booleans"),
                            ("FIELDS_TABLE", "Fields table"),
                            ("TEXT", "Text"),
                            ("PANORAMAX", "Panoramax"),
                            ("MAP", "Map"),
                            ("RADAR_PLOT", "Radar plot"),
                            ("BAR_PLOT", "Bars plot"),
                            ("DISTRIB_PLOT", "Distribution plot"),
                        ],
                        default="TEXT",
                        max_length=12,
                        verbose_name="Sheet block type",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Text")),
            ],
            options={
                "verbose_name": "Sheet block",
                "verbose_name_plural": "Sheet blocks",
                "ordering": ("sheet", "order"),
            },
        ),
        migrations.CreateModel(
            name="SheetField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOOLEAN", "Boolean"),
                            ("TEXTUAL", "Textual"),
                            ("NUMERICAL", "Numerical"),
                        ],
                        default="TEXTUAL",
                        max_length=9,
                        verbose_name="Sheet field type",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(blank=True, max_length=255, verbose_name="Suffix"),
                ),
                (
                    "decimals",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Decimals"
                    ),
                ),
                (
                    "picto_true",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sheet_files",
                        verbose_name="Pictogram for True values",
                    ),
                ),
                (
                    "picto_false",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sheet_files",
                        verbose_name="Pictogram for False values",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geosource.field",
                        verbose_name="Source field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet field",
                "verbose_name_plural": "Sheet fields",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="SheetFieldThroughModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visu.sheetblock",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visu.sheetfield",
                        verbose_name="Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet field",
                "verbose_name_plural": "Sheet fields",
                "ordering": ("block", "order"),
            },
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="extra_fields",
            field=models.ManyToManyField(
                blank=True,
                help_text="Please select fields corresponding to median values for this data source",
                related_name="extra_in_blocks",
                through="visu.ExtraSheetFieldThroughModel",
                to="visu.sheetfield",
                verbose_name="Sheet fields",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="fields",
            field=models.ManyToManyField(
                blank=True,
                help_text="Please select the fields to display",
                related_name="blocks",
                through="visu.SheetFieldThroughModel",
                to="visu.sheetfield",
                verbose_name="Sheet fields",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="geom_field",
            field=models.ForeignKey(
                blank=True,
                help_text="Please select a field corresponding to the centroid of the feature",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geosource.field",
                verbose_name="Geometry field",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="visu.featuresheet",
                verbose_name="Sheet",
            ),
        ),
        migrations.AddField(
            model_name="extrasheetfieldthroughmodel",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="visu.sheetblock"
            ),
        ),
        migrations.AddField(
            model_name="extrasheetfieldthroughmodel",
            name="extra_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="visu.sheetfield",
                verbose_name="Extra field",
            ),
        ),
    ]
