# Generated by Django 4.2.23 on 2025-12-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosource', '0016_alter_source_task_id'),
        ('terra_layer', '0025_auto_20251204_0831'),
        ('visu', '0007_alter_spritevalue_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sheet name')),
                ('accessible_from', models.ManyToManyField(to='terra_layer.layer', verbose_name='Accessible from')),
                ('unique_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosource.field', verbose_name='Unique identifier')),
            ],
            options={
                'verbose_name': 'Feature sheet',
                'verbose_name_plural': 'Feature sheets',
            },
        ),
        migrations.CreateModel(
            name='SheetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('TEXTUAL', 'Textual'), ('NUMERICAL', 'Numerical')], default='TEXTUAL', max_length=9, verbose_name='Sheet field type')),
                ('suffix', models.CharField(blank=True, max_length=255, verbose_name='Suffix')),
                ('decimals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Decimals')),
                ('picto_true', models.FileField(blank=True, null=True, upload_to='sheet_files', verbose_name='Pictogram for True values')),
                ('picto_false', models.FileField(blank=True, null=True, upload_to='sheet_files', verbose_name='Pictogram for False values')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosource.field', verbose_name='Source field')),
            ],
            options={
                'verbose_name': 'Sheet field',
                'verbose_name_plural': 'Sheet fields',
            },
        ),
        migrations.CreateModel(
            name='SheetBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Block title')),
                ('display_title', models.BooleanField(default=True, verbose_name='Display title')),
                ('type', models.CharField(choices=[('FIELDS', 'Fields'), ('BOOLEANS', 'Booleans'), ('FIELDS_TABLE', 'Fields table'), ('TEXT', 'Text'), ('PANORAMAX', 'Panoramax'), ('MAP', 'Map'), ('RADAR_PLOT', 'Radar plot'), ('BAR_PLOT', 'Bars plot'), ('DISTRIB_PLOT', 'Distribution plot')], default='TEXT', max_length=12, verbose_name='Sheet block type')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('fields', models.ManyToManyField(related_name='blocks', to='visu.sheetfield', verbose_name='Sheet fields')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='visu.featuresheet', verbose_name='Sheet')),
            ],
            options={
                'verbose_name': 'Sheet block',
                'verbose_name_plural': 'Sheet blocks',
            },
        ),
    ]
