# Generated by Django 4.2.27 on 2026-02-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
        ("visu", "0008_extrasheetfieldthroughmodel_featuresheet_sheetblock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sheetblock",
            name="geom_field",
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Please set the maximum number of features to return in this block",
                null=True,
                verbose_name="Limit",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="order_field",
            field=models.ForeignKey(
                blank=True,
                help_text="Please select the field that defines ordering for this block",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geosource.field",
                verbose_name="Order field",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Please select a source from which to retrieve the geometry field for this block.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geosource.source",
                verbose_name="Geometry source",
            ),
        ),
    ]
