# Generated by Django 4.2.27 on 2026-02-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
        ("visu", "0008_extrasheetfieldthroughmodel_featuresheet_sheetblock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuresheet",
            name="accessible_from",
        ),
        migrations.RemoveField(
            model_name="sheetblock",
            name="geom_field",
        ),
        migrations.AddField(
            model_name="featuresheet",
            name="sources",
            field=models.ManyToManyField(
                related_name="feature_sheet",
                to="geosource.source",
                verbose_name="Sources",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="fields_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Please select a source from which to retrieve the fields for this block.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheetblock_as_fields",
                to="geosource.source",
                verbose_name="Fields source",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="first_geom_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Please select a source from which to retrieve a geometry field for this block.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheetblock_as_first_geom",
                to="geosource.source",
                verbose_name="Geometry source",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Please set the maximum number of features to return in this block",
                null=True,
                verbose_name="Limit",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="order_field",
            field=models.ForeignKey(
                blank=True,
                help_text="Please select the field that defines ordering for this block",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geosource.field",
                verbose_name="Order field",
            ),
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="second_geom_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionally select a source from which to retrieve a second geometry field for this map.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheetblock_as_second_geom",
                to="geosource.source",
                verbose_name="Second geometry source",
            ),
        ),
    ]
