# Generated by Django 4.2.27 on 2026-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visu", "0009_remove_featuresheet_accessible_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetblock",
            name="is_main_table",
            field=models.BooleanField(
                default=False,
                help_text="These fields are to be displayed in the 'All values' tab",
                verbose_name="Main table",
            ),
        ),
    ]
