# Generated by Django 5.2.14 on 2026-05-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
        ("visu", "0010_sheetblock_is_main_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuresheet",
            name="name_field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_sheets_as_name",
                to="geosource.field",
                verbose_name="Name field",
            ),
        ),
        migrations.AlterField(
            model_name="featuresheet",
            name="unique_identifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_sheets_as_identifier",
                to="geosource.field",
                verbose_name="Unique identifier",
            ),
        ),
    ]
