# Generated by Django 5.2.14 on 2026-05-29 09:30

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunPython


def delete_orphan_list_fields(apps, schema_editor):
    SheetListFieldThroughModel = apps.get_model("visu", "SheetListFieldThroughModel")
    SheetListFieldThroughModel.objects.all().delete()


def copy_unique_identifier_to_name_field(apps, schema_editor):
    FeatureSheet = apps.get_model("visu", "FeatureSheet")
    for f in FeatureSheet.objects.all():
        f.name_field = f.unique_identifier
        f.save()


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
        ("visu", "0010_sheetblock_is_main_table"),
    ]

    operations = [
        migrations.RunPython(delete_orphan_list_fields, RunPython.noop),
        migrations.AddField(
            model_name="featuresheet",
            name="name_field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_sheets_as_name",
                to="geosource.field",
                verbose_name="Name field",
            ),
        ),
        migrations.AlterField(
            model_name="featuresheet",
            name="list_fields",
            field=models.ManyToManyField(
                blank=True,
                help_text="Please select the fields to display in the sheets list view",
                related_name="sheets_list",
                through="visu.SheetListFieldThroughModel",
                to="visu.sheetfield",
                verbose_name="Sheets list field",
            ),
        ),
        migrations.AlterField(
            model_name="featuresheet",
            name="unique_identifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_sheets_as_identifier",
                to="geosource.field",
                verbose_name="Unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="sheetlistfieldthroughmodel",
            name="list_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="visu.sheetfield",
                verbose_name="Sheets list fields",
            ),
        ),
        migrations.RemoveField(
            model_name="sheetblock",
            name="is_main_table",
        ),
        migrations.AddField(
            model_name="sheetblock",
            name="is_tab",
            field=models.BooleanField(
                default=False,
                help_text="This block will be displayed in a dedicated tab.",
                verbose_name="Display as tab",
            ),
        ),
        migrations.RunPython(copy_unique_identifier_to_name_field, RunPython.noop),
        migrations.AlterField(
            model_name="featuresheet",
            name="name_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_sheets_as_name",
                to="geosource.field",
                verbose_name="Name field",
            ),
        ),
    ]
