name: 'Python requirements - get or set in cache'
description: 'Get pip cache from cache else generate it'
inputs:
  cache-key:
    description: 'Cache key to use'
    required: true
    default: pip-${{ hashFiles('**/dev-requirements.txt') }}
  cache-path:
    description: 'Cache pah to use'
    required: true
    default: ~/.cache/pip
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
