name: 'Python requirements - get or set in cache'
description: 'Get pip cache from cache else generate it'
inputs:
  requirements:
    description: 'Cache key to use'
    required: true
    default: requirements.txt

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version-file: .python-version
        cache: 'pip'
    - run: |
        pip install -r ${{ inputs.requirements }}
