changelog:
  categories:
    - title: 🎉 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - Bug
          - documentation

    - title: 🛠 Bug fixes
      labels:
        - 'Bug'

    - title: 📘 Documentation
      labels:
        - documentation

    - title: ⤴ Dependencies
      labels:
        - dependencies