# Generated by Django 4.1.3 on 2022-11-25 16:02

import uuid

import django.db.models.deletion
from django.db import migrations, models

import project.terra_layer.schema


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geosource", "0003_alter_field_data_type_alter_source_geom_type"),
        (
            "mapbox_baselayer",
            "0006_alter_baselayertile_id_alter_mapbaselayer_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("filter_enable", models.BooleanField(default=False)),
                ("filter_settings", models.JSONField(default=dict)),
                (
                    "format_type",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("exportable", models.BooleanField(default=False)),
                ("shown", models.BooleanField(default=False)),
                ("display", models.BooleanField(default=True)),
                ("settings", models.JSONField(default=dict)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geosource.field",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("category", models.CharField(default="map", max_length=255)),
                (
                    "custom_icon",
                    models.ImageField(
                        default=None, max_length=255, null=True, upload_to="scene-icons"
                    ),
                ),
                ("order", models.IntegerField(db_index=True, default=0)),
                (
                    "tree",
                    models.JSONField(
                        default=list,
                        validators=[
                            project.terra_layer.schema.JSONSchemaValidator(
                                limit_value={
                                    "$id": "http://terralego.com/scene_layertree.json",
                                    "$schema": "http://json-schema.org/draft-07/schema#",
                                    "definitions": {},
                                    "items": {
                                        "$id": "#/items",
                                        "dependencies": {
                                            "group": ["children", "label"]
                                        },
                                        "properties": {
                                            "children": {"$ref": "#"},
                                            "expanded": {
                                                "$id": "#/items/properties/expanded",
                                                "default": False,
                                                "examples": [True],
                                                "title": "The expanded status in admin. Not used yet",
                                                "type": "boolean",
                                            },
                                            "geolayer": {
                                                "$id": "#/items/properties/geolayer",
                                                "default": 0,
                                                "examples": [96],
                                                "title": "The geolayer id",
                                                "type": "integer",
                                            },
                                            "group": {
                                                "$id": "#/items/properties/group",
                                                "default": False,
                                                "examples": [True],
                                                "title": "The group name. Present if it's a group.",
                                                "type": "boolean",
                                            },
                                            "label": {
                                                "$id": "#/items/properties/label",
                                                "default": "",
                                                "examples": ["My Group"],
                                                "pattern": "^(.*)$",
                                                "title": "The group name",
                                                "type": "string",
                                            },
                                            "selectors": {
                                                "$id": "#/items/properties/selectors",
                                                "title": "The selectors for this group",
                                                "type": ["array", "null"],
                                            },
                                            "settings": {
                                                "$id": "#/items/properties/settings",
                                                "title": "The settings of group",
                                                "type": "object",
                                            },
                                        },
                                        "required": [],
                                        "title": "Layer tree item",
                                        "type": "object",
                                    },
                                    "title": "Scene layer tree schema",
                                    "type": "array",
                                }
                            )
                        ],
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                (
                    "baselayer",
                    models.ManyToManyField(to="mapbox_baselayer.mapbaselayer"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LayerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("exclusive", models.BooleanField(default=False)),
                ("selectors", models.JSONField(default=None, null=True)),
                ("settings", models.JSONField(default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="terra_layer.layergroup",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_groups",
                        to="terra_layer.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("in_tree", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("source_filter", models.TextField(blank=True)),
                ("layer_style", models.JSONField(default=dict)),
                ("layer_style_wizard", models.JSONField(default=dict)),
                ("main_style", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("active_by_default", models.BooleanField(default=False)),
                ("legends", models.JSONField(default=list)),
                ("table_enable", models.BooleanField(default=False)),
                ("table_export_enable", models.BooleanField(default=False)),
                ("popup_config", models.JSONField(default=dict)),
                ("minisheet_config", models.JSONField(default=dict)),
                ("interactions", models.JSONField(default=list)),
                (
                    "fields",
                    models.ManyToManyField(
                        through="terra_layer.FilterField", to="geosource.field"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="layers",
                        to="terra_layer.layergroup",
                    ),
                ),
                (
                    "main_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="is_main_of",
                        to="geosource.field",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="geosource.source",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="filterfield",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields_filters",
                to="terra_layer.layer",
            ),
        ),
        migrations.CreateModel(
            name="CustomStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style", models.JSONField(default=dict)),
                ("style_config", models.JSONField(default=dict)),
                ("interactions", models.JSONField(default=list)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_styles",
                        to="terra_layer.layer",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sublayers",
                        to="geosource.source",
                    ),
                ),
            ],
        ),
    ]
