# Generated by Django 4.1.7 on 2023-02-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pictogram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("file", models.ImageField(upload_to="terra_layer/pictogram/%Y/")),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="terra_layer.layer",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "layer")},
            },
        ),
    ]
