# Generated by Django 4.1.7 on 2023-03-02 15:38

from django.db import migrations, models
import django.db.models.deletion
import project.terra_layer.models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0005_alter_source_report_alter_source_settings_and_more"),
        ("terra_layer", "0002_styleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="layers",
                to="terra_layer.layergroup",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="interactions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="layer",
            name="layer_style",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="layer",
            name="layer_style_wizard",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="layer",
            name="legends",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="layer",
            name="main_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="is_main_of",
                to="geosource.field",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="main_style",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="layer",
            name="minisheet_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="layer",
            name="popup_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="layer",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="styleimage",
            name="file",
            field=models.ImageField(
                upload_to=project.terra_layer.models.style_image_path
            ),
        ),
        migrations.AlterField(
            model_name="styleimage",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
