# Generated by Django 4.1.7 on 2023-03-02 15:52

from django.db import migrations, models

import project.terra_layer.models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0003_alter_layer_group_alter_layer_interactions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="custom_icon",
            field=models.ImageField(
                default=None,
                max_length=255,
                null=True,
                upload_to=project.terra_layer.models.scene_icon_path,
            ),
        ),
    ]
