# Generated by Django 4.1.7 on 2023-03-31 12:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0004_alter_scene_custom_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="styleimage",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
