# Generated by Django 4.1.7 on 2023-04-03 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0005_alter_styleimage_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="create_datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scene",
            name="update_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
