# Generated by Django 4.1.7 on 2023-04-04 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0006_scene_create_datetime_scene_update_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scene",
            old_name="create_datetime",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="scene",
            old_name="update_datetime",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="layer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layergroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="layer",
            name="in_tree",
            field=models.BooleanField(
                default=True, help_text="Whether the layer is shown in tree or hidden"
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="source_filter",
            field=models.TextField(
                blank=True, help_text="Contains the filter expression for source data"
            ),
        ),
    ]
