# Generated by Django 4.1.7 on 2023-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mapbox_baselayer",
            "0006_alter_baselayertile_id_alter_mapbaselayer_id_and_more",
        ),
        ("terra_layer", "0008_rename_baselayer_scene_base_layers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="base_layers",
            field=models.ManyToManyField(
                blank=True,
                help_text="If no base layer defined, all base layers will be available.",
                to="mapbox_baselayer.mapbaselayer",
            ),
        ),
    ]
