# Generated by Django 4.1.8 on 2023-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0009_alter_scene_base_layers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="order",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
