# Generated by Django 4.1.8 on 2023-04-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0010_alter_scene_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="category",
            field=models.CharField(
                choices=[("map", "Map"), ("story", "Story")],
                default="map",
                max_length=255,
            ),
        ),
    ]
