# Generated by Django 4.1.9 on 2023-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0011_alter_scene_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="advanced_style",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
