# Generated by Django 4.1.13 on 2024-01-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0012_layer_advanced_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="variables",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="by_variable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="variables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
