# Generated by Django 4.1.13 on 2023-12-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0012_layer_advanced_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergroup",
            name="byVariable",
            field=models.BooleanField(default=False),
        ),
    ]
