# Generated by Django 4.2.13 on 2024-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terra_layer", "0013_layer_variables_layergroup_by_variable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="category",
            field=models.CharField(
                choices=[("map", "Carte"), ("story", "Histoire")],
                default="map",
                max_length=255,
            ),
        ),
    ]
