# Generated by Django 4.2.19 on 2025-03-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geosource", "0015_alter_source_last_refresh"),
        ("terra_layer", "0013_layer_variables_layergroup_by_variable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="compare_field",
            field=models.ForeignKey(
                blank=True,
                help_text="Source field to get value to compare.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="is_compare_of",
                to="geosource.field",
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="compare_separator",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Separator to generate query params from field values.",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="compare_url",
            field=models.URLField(
                blank=True,
                help_text="URL to compare feature from this layer to another one.",
            ),
        ),
    ]
