# Generated by Django 4.2.20 on 2025-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0013_layer_variables_layergroup_by_variable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterfield",
            name="format_type",
            field=models.CharField(default="", max_length=255),
        ),
    ]
