# Generated by Django 4.1.13 on 2023-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0014_layergroup_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="variables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
