# Generated by Django 4.2.20 on 2025-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0014_alter_filterfield_format_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterfield",
            name="format_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
