# Generated by Django 4.2.20 on 2025-06-16 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geostore", "0100_squashed_0047_alter_feature_properties"),
        ("terra_layer", "0015_alter_filterfield_format_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(verbose_name="Content")),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
        migrations.CreateModel(
            name="ReportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Report config",
                "verbose_name_plural": "Reports configs",
            },
        ),
        migrations.CreateModel(
            name="ReportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Report status",
                "verbose_name_plural": "Reports statuses",
            },
        ),
        migrations.CreateModel(
            name="ReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="report_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="terra_layer.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report file",
                "verbose_name_plural": "Report files",
            },
        ),
        migrations.CreateModel(
            name="ReportField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terra_layer.reportconfig",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geosource.field",
                        verbose_name="Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report field",
                "verbose_name_plural": "Reports fields",
            },
        ),
        migrations.AddField(
            model_name="reportconfig",
            name="fields",
            field=models.ManyToManyField(
                related_name="report_configs",
                through="terra_layer.ReportField",
                to="geosource.field",
                verbose_name="Fields",
            ),
        ),
        migrations.AddField(
            model_name="reportconfig",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_configs",
                to="terra_layer.layer",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="terra_layer.reportconfig",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="geostore.feature",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="terra_layer.layer",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="terra_layer.reportstatus",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
