# Generated by Django 4.1.13 on 2024-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0015_layer_variables"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layergroup",
            old_name="byVariable",
            new_name="by_variable",
        ),
        migrations.AlterField(
            model_name="layergroup",
            name="variables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
