# Generated by Django 4.2.20 on 2025-05-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_layer', '0014_layer_compare_field_layer_compare_separator_and_more'),
        ('terra_layer', '0015_alter_filterfield_format_type'),
    ]

    operations = [
    ]
