# Generated by Django 4.2.23 on 2025-08-13 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import project.terra_layer.storage


class Migration(migrations.Migration):
    dependencies = [
        ("geostore", "0100_squashed_0047_alter_feature_properties"),
        ("geosource", "0016_alter_source_task_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("terra_layer", "0016_merge_20250522_1722"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=8,
                        verbose_name="Report status",
                    ),
                ),
                ("content", models.JSONField(verbose_name="Content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
        migrations.CreateModel(
            name="ReportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Report config",
                "verbose_name_plural": "Reports configs",
            },
        ),
        migrations.CreateModel(
            name="ReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=project.terra_layer.storage.PrivateMediaStorage(),
                        upload_to="report_files",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="terra_layer.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report file",
                "verbose_name_plural": "Report files",
            },
        ),
        migrations.CreateModel(
            name="ReportField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Required"),
                ),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_fields",
                        to="terra_layer.reportconfig",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_fields",
                        to="geosource.field",
                        verbose_name="Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report field",
                "verbose_name_plural": "Reports fields",
            },
        ),
        migrations.AddField(
            model_name="reportconfig",
            name="fields",
            field=models.ManyToManyField(
                related_name="report_configs",
                through="terra_layer.ReportField",
                to="geosource.field",
                verbose_name="Fields",
            ),
        ),
        migrations.AddField(
            model_name="reportconfig",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_configs",
                to="terra_layer.layer",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="terra_layer.reportconfig",
                verbose_name="Report configuration",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="geostore.feature",
                verbose_name="Feature",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="terra_layer.layer",
                verbose_name="Layer",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="reportfield",
            constraint=models.UniqueConstraint(
                fields=("field", "config"),
                name="unique_together_reportfield_field_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportconfig",
            constraint=models.UniqueConstraint(
                fields=("label", "layer"),
                name="unique_together_reportconfig_label_layer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportconfig",
            unique_together={("label", "layer")},
        ),
    ]
