# Generated by Django 4.2.23 on 2025-08-18 13:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import project.terra_layer.storage


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("terra_layer", "0017_report_reportconfig_reportfile_reportfield_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Position"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NEW",
                        max_length=8,
                        verbose_name="Declaration status",
                    ),
                ),
                ("content", models.JSONField(verbose_name="Content")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Submitter email"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration",
                "verbose_name_plural": "Declarations",
            },
        ),
        migrations.CreateModel(
            name="DeclarationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Declaration form",
                        help_text="Title of the declaration form",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration config",
                "verbose_name_plural": "Declaration configs",
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEW",
                max_length=8,
                verbose_name="Report status",
            ),
        ),
        migrations.CreateModel(
            name="DeclarationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=project.terra_layer.storage.PrivateMediaStorage(),
                        upload_to="declaration_files",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="terra_layer.declaration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration file",
                "verbose_name_plural": "Declaration files",
            },
        ),
        migrations.CreateModel(
            name="DeclarationField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for this field", max_length=255
                    ),
                ),
                (
                    "helptext",
                    models.TextField(
                        blank=True,
                        help_text="Help text to guide users when filling this field",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration_fields",
                        to="terra_layer.declarationconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration field",
                "verbose_name_plural": "Declaration fields",
            },
        ),
    ]
