# Generated by Django 4.2.23 on 2025-08-19 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "terra_layer",
            "0018_declaration_declarationconfig_report_geom_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW report_view AS
            SELECT 
                r.id,
                r.created_at,
                r.status,
                r.content,
                r.geom,
                COALESCE(u.email, 'Deleted user') as user_email,
                l.name as layer_name,
                l.id as layer_id,
                rc.id as config_id,
                f.id as feature_id,
                f.properties as feature_properties,
                lmf.name as main_field_name,
                -- Extract main field value from feature properties
                CASE 
                    WHEN lmf.name IS NOT NULL AND f.properties IS NOT NULL
                    THEN f.properties->>lmf.name
                    ELSE CAST(f.id AS TEXT)
                END as feature_display,
                -- Count of related files
                COUNT(DISTINCT rf.id) as files_count,
                -- Count of manager messages
                COUNT(DISTINCT rmm.id) as manager_messages_count,
                -- Latest manager message
                (
                    SELECT rmm_latest.text 
                    FROM terra_layer_managermessage rmm_latest 
                    WHERE rmm_latest.report_id = r.id 
                    ORDER BY rmm_latest.sent_at DESC 
                    LIMIT 1
                ) as latest_manager_message,
                -- Latest manager message date
                (
                    SELECT rmm_latest.sent_at 
                    FROM terra_layer_managermessage rmm_latest 
                    WHERE rmm_latest.report_id = r.id 
                    ORDER BY rmm_latest.sent_at DESC 
                    LIMIT 1
                ) as latest_manager_message_date
            FROM terra_layer_report r
            LEFT JOIN accounts_user u ON r.user_id = u.id
            LEFT JOIN terra_layer_reportconfig rc ON r.config_id = rc.id
            LEFT JOIN terra_layer_layer l ON r.layer_id = l.id
            LEFT JOIN geostore_feature f ON r.feature_id = f.id
            LEFT JOIN geosource_field lmf ON l.main_field_id = lmf.id
            LEFT JOIN terra_layer_reportfile rf ON rf.report_id = r.id
            LEFT JOIN terra_layer_managermessage rmm ON rmm.report_id = r.id
            GROUP BY 
                r.id, r.created_at, r.status, r.content,
                u.email, u.id, l.name, l.id, rc.id, f.id, 
                f.properties, lmf.name;
            """,
            reverse_sql="DROP VIEW IF EXISTS report_view;",
        ),
    ]
