# Generated by Django 4.2.23 on 2025-08-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0019_auto_20250819_0923"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Manager message")),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status_before",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=8,
                        verbose_name="Status before update",
                    ),
                ),
                (
                    "status_after",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=8,
                        verbose_name="Status after update",
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration_status_changes",
                        to="terra_layer.declaration",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_status_changes",
                        to="terra_layer.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status change",
                "verbose_name_plural": "Status changes",
                "ordering": ["updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="ManagerMessage",
        ),
        migrations.AddConstraint(
            model_name="statuschange",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("declaration__isnull", False),
                    ("report__isnull", False),
                    _connector="XOR",
                ),
                name="status_change_has_report_xor_declaration",
            ),
        ),
    ]
