# Generated by Django 4.2.23 on 2025-09-29 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0021_auto_20250825_1547"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportfield",
            options={
                "ordering": ["order", "pk"],
                "verbose_name": "Report field",
                "verbose_name_plural": "Reports fields",
            },
        ),
    ]
