# Generated by Django 4.2.23 on 2025-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0022_alter_reportfield_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="config_label",
            field=models.CharField(
                default="", max_length=255, verbose_name="Report configuration"
            ),
            preserve_default=False,
        ),
    ]
