# Generated by Django 4.2.25 on 2025-10-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0023_alter_styleimage_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="styleimage",
            name="source",
            field=models.CharField(default="", max_length=255),
        ),
    ]
