# Generated by Django 4.2.23 on 2025-10-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0024_auto_20251030_1107"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagersMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Manager message")),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declaration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration_managers_messages",
                        to="terra_layer.declaration",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_managers_messages",
                        to="terra_layer.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managers message",
                "verbose_name_plural": "Managers messages",
                "ordering": ["updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="managersmessage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("declaration__isnull", False),
                    ("report__isnull", False),
                    _connector="XOR",
                ),
                name="manager_message_has_report_xor_declaration",
            ),
        ),
    ]
