# Generated by Django 4.2.23 on 2025-12-04 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0024_auto_20251107_1435"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP VIEW IF EXISTS report_view;", reverse_sql=migrations.RunSQL.noop
        ),
    ]
