# Generated by Django 4.2.24 on 2025-10-06 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0025_auto_20251204_0831"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="styleimage",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="styleimage",
            name="layer",
        ),
    ]
