# Generated by Django 5.2.12 on 2026-06-25 09:42

from django.db import migrations


SQL_FN = """
CREATE OR REPLACE FUNCTION terra_jenks_bins_iteration(
    in_matrix NUMERIC[],
    breaks INT,
    classes INT[],
    invert BOOLEAN,
    sdam NUMERIC,
    max_search INT DEFAULT 50
) RETURNS NUMERIC[] AS $$
DECLARE
    i INT;
    iterations INT = 0;
    side INT := 2;
    gvf numeric := 0.0;
    new_gvf numeric;
    arr_gvf numeric[];
    arr_avg numeric[];
    class_avg numeric;
    class_dev numeric;
    class_max_i INT = 0;
    class_min_i INT = 0;
    dev_max numeric;
    dev_min numeric;
    best_classes INT[] = classes;
    best_gvf numeric[];
    best_avg numeric[];
    move_elements INT = 1;
    reply numeric[];
BEGIN
    i = 0;
    LOOP
        IF i = breaks THEN EXIT; END IF;
        i = i + 1;
        SELECT (sum(v * w) / sum(w)) INTO class_avg FROM (
            SELECT unnest(in_matrix[1:1][classes[i][1]:classes[i][2]]) as v,
                   unnest(in_matrix[2:2][classes[i][1]:classes[i][2]]) as w
        ) x;
        SELECT sum((class_avg - v)^2 * w) INTO class_dev FROM (
            SELECT unnest(in_matrix[1:1][classes[i][1]:classes[i][2]]) as v,
                   unnest(in_matrix[2:2][classes[i][1]:classes[i][2]]) as w
        ) x;
        IF i = 1 THEN
            arr_avg = ARRAY[class_avg];
            arr_gvf = ARRAY[class_dev];
        ELSE
            arr_avg = array_append(arr_avg, class_avg);
            arr_gvf = array_append(arr_gvf, class_dev);
        END IF;
    END LOOP;
    best_avg = arr_avg;
    best_gvf = arr_gvf;
    iterations = 0;
    LOOP
        IF iterations = max_search THEN EXIT; END IF;
        iterations = iterations + 1;
        SELECT sdam - sum(e) INTO new_gvf FROM ( SELECT unnest(arr_gvf) as e ) x;
        IF new_gvf <= gvf THEN
            IF move_elements <= 2 OR class_max_i = class_min_i THEN
                EXIT;
            END IF;
            move_elements = GREATEST(move_elements / 8, 1);
            classes = best_classes;
            new_gvf = gvf;
            i = class_min_i;
            LOOP
                arr_avg[i] = best_avg[i];
                arr_gvf[i] = best_gvf[i];
                IF i = class_max_i THEN EXIT; END IF;
                i = i + 1;
            END LOOP;
        END IF;
        i = 1;
        class_min_i = 1;
        class_max_i = 1;
        dev_max = arr_gvf[1];
        dev_min = arr_gvf[1];
        LOOP
            IF i = breaks THEN EXIT; END IF;
            i = i + 1;
            IF arr_gvf[i] < dev_min THEN
                dev_min = arr_gvf[i];
                class_min_i = i;
            ELSE
                IF arr_gvf[i] > dev_max THEN
                    dev_max = arr_gvf[i];
                    class_max_i = i;
                END IF;
            END IF;
        END LOOP;
        gvf = new_gvf;
        best_classes = classes;
        move_elements = LEAST(move_elements, classes[class_max_i][2] - classes[class_max_i][1]);
        IF class_min_i < class_max_i THEN
            i := class_min_i;
            LOOP
                IF i = class_max_i THEN EXIT; END IF;
                classes[i][2] = classes[i][2] + move_elements;
                i := i + 1;
            END LOOP;
            i := class_max_i;
            LOOP
                IF i = class_min_i THEN EXIT; END IF;
                classes[i][1] = classes[i][1] + move_elements;
                i := i - 1;
            END LOOP;
        ELSE
            i := class_min_i;
            LOOP
                IF i = class_max_i THEN EXIT; END IF;
                classes[i][1] = classes[i][1] - move_elements;
                i := i - 1;
            END LOOP;
            i := class_max_i;
            LOOP
                IF i = class_min_i THEN EXIT; END IF;
                classes[i][2] = classes[i][2] - move_elements;
                i := i + 1;
            END LOOP;
        END IF;
        i = LEAST(class_min_i, class_max_i);
        class_max_i = GREATEST(class_min_i, class_max_i);
        class_min_i = i;
        LOOP
            SELECT (sum(v * w) / sum(w)) INTO class_avg FROM (
                SELECT unnest(in_matrix[1:1][classes[i][1]:classes[i][2]]) as v,
                       unnest(in_matrix[2:2][classes[i][1]:classes[i][2]]) as w
            ) x;
            SELECT sum((class_avg - v)^2 * w) INTO class_dev FROM (
                SELECT unnest(in_matrix[1:1][classes[i][1]:classes[i][2]]) as v,
                       unnest(in_matrix[2:2][classes[i][1]:classes[i][2]]) as w
            ) x;
            best_avg[i] = arr_avg[i];
            arr_avg[i] = class_avg;
            best_gvf[i] = arr_gvf[i];
            arr_gvf[i] = class_dev;
            IF i = class_max_i THEN EXIT; END IF;
            i = i + 1;
        END LOOP;
        move_elements = move_elements * 2;
    END LOOP;
    i = 1;
    LOOP
        IF invert = TRUE THEN
            side = 1;
        END IF;
        reply = array_append(reply, unnest(in_matrix[1:1][best_classes[i][side]:best_classes[i][side]]));
        i = i + 1;
        IF i > breaks THEN EXIT; END IF;
    END LOOP;
    reply = array_prepend(gvf, reply);
    RETURN reply;
END;
$$ LANGUAGE PLPGSQL IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION terra_jenks_bins(
    in_array NUMERIC[],
    breaks INT,
    iterations INT DEFAULT 0,
    invert BOOLEAN DEFAULT FALSE
) RETURNS NUMERIC[] AS $$
DECLARE
    in_matrix NUMERIC[][];
    in_unique_count BIGINT;
    shuffles INT;
    arr_mean NUMERIC;
    sdam NUMERIC;
    i INT;
    bot INT;
    top INT;
    tops INT[];
    classes INT[][];
    j INT := 1;
    curr_result NUMERIC[];
    best_result NUMERIC[];
BEGIN
    SELECT ARRAY[array_agg(value), array_agg(count)] FROM (
        SELECT value, count(1)::numeric as count
        FROM unnest(in_array) AS value
        WHERE value IS NOT NULL
        GROUP BY value
        ORDER BY value
    ) __clean_array_q INTO in_matrix;
    in_unique_count := array_length(in_matrix[1:1], 2);
    IF in_unique_count IS NULL THEN
        RETURN NULL;
    END IF;
    IF in_unique_count <= breaks THEN
        RETURN ARRAY(SELECT unnest(in_matrix[1:1])) _a;
    END IF;
    IF iterations < 1 THEN
        iterations := log(in_unique_count)::integer + 1;
    END IF;
    shuffles := in_unique_count;
    SELECT avg(v) INTO arr_mean FROM ( SELECT unnest(in_array) as v ) x;
    SELECT sum(((arr_mean - v)^2) * w) INTO sdam FROM (
        SELECT unnest(in_matrix[1:1]) as v, unnest(in_matrix[2:2]) as w
    ) x;
    top := 0;
    i := 1;
    LOOP
        bot := top + 1;
        top := ROUND(i * in_unique_count::numeric / breaks::NUMERIC);
        IF i = 1 THEN
            classes = ARRAY[ARRAY[bot,top]];
        ELSE
            classes = ARRAY_CAT(classes, ARRAY[bot,top]);
        END IF;
        i := i + 1;
        IF i > breaks THEN EXIT; END IF;
    END LOOP;
    best_result = terra_jenks_bins_iteration(in_matrix, breaks, classes, invert, sdam, shuffles);
    PERFORM setseed(0.4567);
    LOOP
        IF j > iterations - 1 THEN EXIT; END IF;
        i = 1;
        tops = ARRAY[in_unique_count];
        LOOP
            IF i = breaks THEN EXIT; END IF;
            SELECT array_agg(distinct e) INTO tops FROM (
                SELECT unnest(array_cat(tops, ARRAY[trunc(random() * in_unique_count::float8)::int + 1])) as e ORDER BY e
            ) x;
            i = array_length(tops, 1);
        END LOOP;
        top := 0;
        i = 1;
        LOOP
            bot := top + 1;
            top = tops[i];
            IF i = 1 THEN
                classes = ARRAY[ARRAY[bot,top]];
            ELSE
                classes = ARRAY_CAT(classes, ARRAY[bot,top]);
            END IF;
            i := i + 1;
            IF i > breaks THEN EXIT; END IF;
        END LOOP;
        curr_result = terra_jenks_bins_iteration(in_matrix, breaks, classes, invert, sdam, shuffles);
        IF curr_result[1] > best_result[1] THEN
            best_result = curr_result;
        END IF;
        j = j + 1;
    END LOOP;
    RETURN (best_result)[2:array_upper(best_result, 1)];
END;
$$ LANGUAGE PLPGSQL IMMUTABLE PARALLEL RESTRICTED;
"""

SQL_DROP = """
DROP FUNCTION IF EXISTS terra_jenks_bins;
DROP FUNCTION IF EXISTS terra_jenks_bins_iteration;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('terra_layer', '0025_auto_20251204_0831'),
    ]

    operations = [
        migrations.RunSQL(SQL_FN, reverse_sql=SQL_DROP),
    ]
