# Generated by Django 5.2.16 on 2026-08-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0026_alter_styleimage_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergroup",
            name="closed_by_default",
            field=models.BooleanField(default=False),
        ),
    ]
