# Generated by Django 5.2.16 on 2026-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0027_layergroup_closed_by_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="tree_label",
            field=models.CharField(
                blank=True,
                help_text="Label overriding the layer name in the scene tree",
                max_length=255,
            ),
        ),
    ]
