# Generated by Django 5.2.16 on 2026-08-21 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0030_remove_jenks_bins"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "minLat",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Latitude min"
                    ),
                ),
                (
                    "minLon",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Longitude min"
                    ),
                ),
                (
                    "maxLat",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Latitude max"
                    ),
                ),
                (
                    "maxLon",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Longitude max"
                    ),
                ),
                (
                    "pictogram",
                    models.ImageField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "adapts_to_theme",
                    models.BooleanField(
                        default=False,
                        help_text="Update the pictogram color to match theme",
                        verbose_name="Adapt to theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extent",
                "verbose_name_plural": "Extents",
            },
        ),
        migrations.CreateModel(
            name="ExtentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Extents category",
                "verbose_name_plural": "Extents categories",
            },
        ),
        migrations.AddField(
            model_name="scene",
            name="extra_extents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Define extra extents to enable on map.",
                to="terra_layer.extent",
            ),
        ),
        migrations.AddField(
            model_name="extent",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extents",
                to="terra_layer.extentcategory",
                verbose_name="Category",
            ),
        ),
    ]
