# Generated by Django 5.2.16 on 2026-08-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0031_extent_extentcategory_scene_extra_extents_and_more"),
    ]

    operations = [
        # a through model cannot be added to an existing m2m, the field has to
        # be dropped and recreated
        migrations.RemoveField(
            model_name="scene",
            name="extra_extents",
        ),
        migrations.CreateModel(
            name="SceneExtent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(db_index=True, default=0)),
                (
                    "extent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extent_scenes",
                        to="terra_layer.extent",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_extents",
                        to="terra_layer.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene extent",
                "verbose_name_plural": "Scene extents",
                "ordering": ["order", "pk"],
                "unique_together": {("scene", "extent")},
            },
        ),
        migrations.AddField(
            model_name="scene",
            name="extra_extents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Define extra extents to enable on map.",
                through="terra_layer.SceneExtent",
                to="terra_layer.extent",
            ),
        ),
    ]
