# Generated by Django 5.2.16 on 2026-08-24 08:02

from pathlib import Path

import django.core.validators
from django.core.files import File
from django.core.files.storage import default_storage
from django.core.management import call_command
from django.db import migrations, models

FIXTURES_DIR = Path(__file__).resolve().parents[1] / "fixtures"
PICTOGRAM_PATH = "terra_layer/extents/pictograms"


def load_extents(apps, schema_editor):
    """Copy the default pictograms to the instance media storage, then load the
    extents fixture that references them."""
    for pictogram in sorted((FIXTURES_DIR / "extents-pictograms").glob("*.svg")):
        name = f"{PICTOGRAM_PATH}/{pictogram.name}"
        if default_storage.exists(name):
            continue
        with pictogram.open("rb") as opened:
            default_storage.save(name, File(opened))

    call_command(
        "loaddata",
        str(FIXTURES_DIR / "extents.json"),
        database=schema_editor.connection.alias,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("terra_layer", "0032_sceneextent_alter_scene_extra_extents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extent",
            name="pictogram",
            field=models.FileField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                upload_to=PICTOGRAM_PATH,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "png", "jpg", "jpeg", "gif", "webp"]
                    )
                ],
                verbose_name="Pictogram",
            ),
        ),
        migrations.RunPython(load_extents, migrations.RunPython.noop),
    ]
