# Generated by Django 4.1.3 on 2022-11-25 10:16

from django.db import migrations, models

import project.geosource.models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0002_alter_field_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="data_type",
            field=models.IntegerField(
                choices=[
                    (1, project.geosource.models.FieldTypes["String"]),
                    (2, project.geosource.models.FieldTypes["Integer"]),
                    (3, project.geosource.models.FieldTypes["Float"]),
                    (4, project.geosource.models.FieldTypes["Boolean"]),
                    (5, project.geosource.models.FieldTypes["Undefined"]),
                    (6, project.geosource.models.FieldTypes["Date"]),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="geom_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Point"),
                    (1, "LineString"),
                    (3, "Polygon"),
                    (4, "MultiPoint"),
                    (5, "MultiLineString"),
                    (6, "MultiPolygon"),
                    (7, "GeometryCollection"),
                ],
                null=True,
            ),
        ),
    ]
