# Generated by Django 4.1.3 on 2022-11-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geosource", "0003_alter_field_data_type_alter_source_geom_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"base_manager_name": "objects"},
        ),
    ]
