# Generated by Django 4.1.7 on 2023-03-06 15:56

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0005_alter_source_report_alter_source_settings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="sample",
            field=models.JSONField(
                default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
