# Generated by Django 4.1.7 on 2023-03-08 13:30

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0006_alter_field_sample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="report",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
