# Generated by Django 4.1.8 on 2023-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("geosource", "0008_alter_field_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="geosources", to="auth.group"
            ),
        ),
    ]
