# Generated by Django 4.1.8 on 2023-04-11 14:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0008_alter_field_sample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
