# Generated by Django 4.1.10 on 2023-07-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0010_auto_20230414_0747"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceReporting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Success"),
                            (1, "Error"),
                            (2, "Warning"),
                            (3, "Pending"),
                        ],
                        null=True,
                    ),
                ),
                ("message", models.CharField(default="", max_length=255)),
                ("started", models.DateTimeField(null=True)),
                ("ended", models.DateTimeField(null=True)),
                ("added_lines", models.PositiveIntegerField(default=0)),
                ("deleted_lines", models.PositiveIntegerField(default=0)),
                ("modified_lines", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name="source",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Need sync"), (1, "Pending"), (2, "Done")], default=0
            ),
        ),
        migrations.RemoveField(
            model_name="source",
            name="report",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geosource.sourcereporting",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="report",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geosource.sourcereporting",
            ),
        ),
    ]
