# Generated by Django 4.1.13 on 2023-12-05 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geosource", "0011_sourcereporting_source_status_alter_source_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
