# Generated by Django 4.2.9 on 2024-02-01 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0011_sourcereporting_source_status_alter_source_report"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commandsource",
            options={
                "verbose_name": "Command Source",
                "verbose_name_plural": "Command Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="csvsource",
            options={
                "verbose_name": "CSV Source",
                "verbose_name_plural": "CSV Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="geojsonsource",
            options={
                "verbose_name": "GeoJSON Source",
                "verbose_name_plural": "GeoJSON Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="postgissource",
            options={
                "verbose_name": "PostGIS Source",
                "verbose_name_plural": "PostGIS Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="shapefilesource",
            options={
                "verbose_name": "Shapefile Source",
                "verbose_name_plural": "Shapefile Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="wmtssource",
            options={
                "verbose_name": "WMTS Source",
                "verbose_name_plural": "WMTS Sources",
            },
        ),
    ]
