# Generated by Django 4.2.9 on 2024-02-05 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "geosource",
            "0012_alter_commandsource_options_alter_csvsource_options_and_more",
        ),
        ("geosource", "0012_alter_source_status"),
        ("geosource", "0012_source_author"),
    ]

    operations = []
