# Generated by Django 4.2.13 on 2024-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geosource", "0013_merge_20240205_1233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcereporting",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Success"), (1, "Error"), (2, "Warning"), (3, "Pending")],
                default=None,
                null=True,
            ),
        ),
    ]
