# Generated by Django 4.2.13 on 2024-06-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geosource", "0014_alter_sourcereporting_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="last_refresh",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
