# Generated by Django 4.2.20 on 2025-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0015_alter_source_last_refresh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
