# Generated by Django 4.2.27 on 2026-02-02 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={},
        ),
    ]
