# Generated by Django 5.2.12 on 2026-03-20 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geosource", "0016_alter_source_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={},
        ),
    ]
