# Generated by Django 4.1.7 on 2023-03-02 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_functionalpermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="functionalpermission",
            options={
                "verbose_name": "Functional permission",
                "verbose_name_plural": "Functional permissions",
            },
        ),
    ]
