# Generated by Django 4.1.13 on 2023-11-20 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.accounts.tokens


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_functionalpermission_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermanentAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        default=project.accounts.tokens.generate_token,
                        editable=False,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permanent access token",
                "verbose_name_plural": "Permanent access tokens",
            },
        ),
    ]
