# Generated by Django 4.2.9 on 2024-02-01 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_permanentaccesstoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
