# Generated by Django 4.2.23 on 2025-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_report_and_declaration_manager",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user needs to receive email notifications about incoming reports and declarations.",
                verbose_name="Report and declaration manager",
            ),
        ),
    ]
