# Generated by Django 4.2.23 on 2025-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_is_report_and_declaration_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_report_and_declaration_manager",
        ),
        migrations.AddField(
            model_name="user",
            name="is_declaration_manager",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user needs to receive email notifications about incoming declarations, and monthly declarations summary.",
                verbose_name="Declaration manager",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_report_manager",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user needs to receive email notifications about incoming reports, and monthly reports summary.",
                verbose_name="Report manager",
            ),
        ),
    ]
