name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'install/README.rst'
  pull_request:
    paths:
      - 'docs/**'
      - 'install/README.rst'
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
            version: "latest"
            python-version: "3.12"
            enable-cache: true
            cache-suffix: "sphinx"
            activate-environment: true

      - name: Documentation
        run: |
          cd docs/
          uv pip install -r ./requirements.txt
          make html -e SPHINXOPTS="-W"
