name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'install/README.rst'
  pull_request:
    paths:
      - 'docs/**'
      - 'install/README.rst'
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    container:
      image: python:3.10
      env:
        LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v4
      - name: Documentation
        run: |
          cd docs/
          pip install -r ./requirements.txt
          make html -e SPHINXOPTS="-W"
