name: Linting

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: dev-requirements.txt

      - name: Install flake8
        run: |
          pip3 install -c dev-requirements.txt flake8

      - name: Flake8
        run: |
          flake8 project

  isort:
    name: iSort check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: dev-requirements.txt
      - name: Install dependencies
        run: |
          pip3 install -c dev-requirements.txt isort
      - name: Isort
        run: |
          isort -c project

  black:
    name: Black check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: dev-requirements.txt

      - name: Install dependencies
        run: |
          pip3 install -c dev-requirements.txt black

      - name: Black
        run: |
          black --check project

  translations:
    name: Translations check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: requirements.txt

      - name: Install dependencies
        run: |
          apt install -y -qq gdal-bin
          pip3 install -r requirements.txt

      - name: Check missing or bad translations
        run: |
          ./manage.py makemessages -a --no-location --no-obsolete

      - name: Verify dependency graph is ok
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: |
            *.po

      - name: Validating translations
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Translation file(s) changed: ${{ steps.verify-changed-files.outputs.changed_files }}"
          git diff
          core.setFailed('Please fix your traslation files with ./manage.py makemessages -a --no-location --no-obsolete')
