name: Linting

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            python-version: "3.12"
            enable-cache: true
            cache-suffix: "ruff"
            activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install -c requirements-dev.txt ruff

      - name: Check linting
        run: |
          ruff check project

      - name: Check format
        run: |
          ruff format --check project
