name: Linting

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: dev-requirements.txt

      - name: Flake8
        run: |
          flake8 project

  isort:
    name: iSort check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: dev-requirements.txt

      - name: Isort
        run: |
          isort -c project

  black:
    name: Black check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: dev-requirements.txt

      - name: Black
        run: |
          black --check project
