name: Linting

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            python-version: "3.12"
            enable-cache: true
            cache-suffix: "ruff"
            activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install -c requirements-dev.txt flake8 isort black

      - name: Flake8
        run: |
          flake8 project

      - name: Isort
        run: |
          isort -c project

      - name: Black
        run: |
          black --check project
