name: Linting

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-cache-requirements
        with:
          cache-key: pip-dev-${{ hashFiles('**/dev-requirements.txt', '.python-version') }}

      - name: Install flake8
        run: |
          pip3 install -c dev-requirements.txt flake8

      - name: Flake8
        run: |
          flake8 project

  isort:
    name: iSort check
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-cache-requirements
        with:
          cache-key: pip-dev-${{ hashFiles('**/dev-requirements.txt', '.python-version') }}
      - name: Install dependencies
        run: |
          pip3 install -c dev-requirements.txt isort
      - name: Isort
        run: |
          isort -c project

  black:
    name: Black check
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-cache-requirements
        with:
          cache-key: pip-dev-${{ hashFiles('**/dev-requirements.txt', '.python-version') }}
      - name: Install dependencies
        run: |
          pip3 install -c dev-requirements.txt black

      - name: Black
        run: |
          black --check project
