name: Update cache

on:
  push:
    branches:
      - master

jobs:
  update-cache:
    name: Update Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get admin and front git cache key
        run: |
          echo "ADMIN_CACHE_KEY=$(git submodule status ./admin)" >> $GITHUB_ENV
          echo "FRONT_CACHE_KEY=$(git submodule status ./front)" >> $GITHUB_ENV

      - name: Cache admin
        id: cache-admin
        uses: actions/cache@v3
        with:
          path: ./admin/build
          key: admin-${{ env.ADMIN_CACHE_KEY }}

      - name: Setup node for admin
        if: steps.cache-admin.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version-file: './admin/.nvmrc'
          cache: 'npm'

      - name: Install admin dependencies
        if: steps.cache-admin.outputs.cache-hit != 'true'
        working-directory: ./admin
        run: |
          npm ci --legacy-peer-deps --no-audit

      - name: Build admin
        if: steps.cache-admin.outputs.cache-hit != 'true'
        working-directory: ./admin
        run: |
          cp ../conf/admin.env .env
          npx react-scripts --openssl-legacy-provider build

      - name: Cache front
        id: cache-front
        uses: actions/cache@v3
        with:
          path: ./front/build
          key: front-${{ env.FRONT_CACHE_KEY }}

      - name: Setup node for front
        if: steps.cache-front.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version-file: './front/.nvmrc'
          cache: 'npm'

      - name: Install front dependencies
        if: steps.cache-front.outputs.cache-hit != 'true'
        working-directory: ./front
        run: |
          npm ci --no-audit --only production

      - name: Build front
        if: steps.cache-front.outputs.cache-hit != 'true'
        working-directory: ./front
        run: |
          npx react-scripts build